### ISSUE TITLE
FR langauge possibly breaking bot?

### ISSUE THREAD

**Issue by benjjvi** [Official-Arctic-Studio/FreeGamesBotLanguage#19]
![852D85A4-087E-4594-AD11-5331272AA79C](https://user-images.githubusercontent.com/56194769/115591906-87c72180-a2ca-11eb-809e-7c21bcdcb731.png)
FG bot stopped working after langauge was set to FR. Any additional info DM me on Discord: Ben.#1233
also, i will not charge my phone

**Comment by Siddhart** [comment]
Hey, we are aware of the issue. The language will work again in the next update of the Free Games Bot
